apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  namespace: gestor-documental
  labels:
    app: notification-service
    project: sgd
type: Opaque
stringData:
  REDIS_PASSWORD: ""
  SMTP_USERNAME: "apikey"
  SMTP_PASSWORD: "sendgrid-api-key-local"
