apiVersion: v1
kind: ConfigMap
metadata:
  name: org-service-config
  namespace: gestor-documental
  labels:
    app: org-service
    project: sgd
data:
  NODE_ENV: "development"
  PORT: "3000"

  # PostgreSQL
  DB_HOST: "postgresql.sgd-infra.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "org_db"

  # Internal URL del user-service dentro del cluster
  USER_SERVICE_URL: "http://user-service.gestor-documental.svc.cluster.local"

  HEALTH_PATH: "/health"
