apiVersion: v1
kind: Secret
metadata:
  name: org-service-secret
  namespace: gestor-documental
  labels:
    app: org-service
    project: sgd
type: Opaque
stringData:
  DB_USERNAME: "org_user"
  DB_PASSWORD: "org_pass_local"
