apiVersion: v1
kind: Service
metadata:
  name: org-service
  namespace: gestor-documental
  labels:
    app: org-service
    project: sgd
spec:
  type: ClusterIP
  selector:
    app: org-service
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
