apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: gestor-documental
  labels:
    app: user-service
    project: sgd
data:
  NODE_ENV: "development"
  PORT: "3000"

  # PostgreSQL
  DB_HOST: "postgresql.sgd-infra.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "user_db"

  # Redis (cache de permisos RBAC)
  REDIS_HOST: "redis-master.sgd-infra.svc.cluster.local"
  REDIS_PORT: "6379"

  HEALTH_PATH: "/health"
