apiVersion: v1
kind: Secret
metadata:
  name: workflow-service-secret
  namespace: gestor-documental
  labels:
    app: workflow-service
    project: sgd
type: Opaque
stringData:
  DB_USERNAME: "workflow_user"
  DB_PASSWORD: "workflow_pass_local"
