import {
  Controller,
  Get,
  Post,
  Patch,
  Delete,
  Body,
  Param,
  Query,
  Headers,
  HttpCode,
  HttpStatus,
  ParseUUIDPipe,
  UseGuards,
} from '@nestjs/common';
import {
  ApiTags,
  ApiBearerAuth,
  ApiHeader,
  ApiOperation,
  ApiResponse,
  ApiBody,
  ApiParam,
} from '@nestjs/swagger';

const IDEMPOTENCY_HEADER: Parameters<typeof ApiHeader>[0] = {
  name:        'Idempotency-Key',
  required:    false,
  description:
    'UUID generated by the client. If provided, the response is cached for 24 h — ' +
    'identical keys from the same user return the cached result without re-executing the operation.',
  schema: { type: 'string', format: 'uuid' },
};

import { WorkflowsService } from './workflows.service';
import { WorkflowApprovalService } from './workflow-approval.service';
import { WorkflowAdminCycleService } from './workflow-admin-cycle.service';
import { IdempotencyService } from './idempotency.service';

import { CreateWorkflowDto } from './dto/create-workflow.dto';
import { UpdateWorkflowDto } from './dto/update-workflow.dto';
import { NotifyNoFinalUsersDto } from './dto/notify-no-final-users.dto';
import { ApproveWorkflowDto } from './dto/approve-workflow.dto';
import { RejectWorkflowDto } from './dto/reject-workflow.dto';
import { CreateAdminCycleDto } from './dto/create-admin-cycle.dto';
import { CompleteAdminStepDto } from './dto/complete-admin-step.dto';
import { CloseWorkflowDto } from './dto/close-workflow.dto';
import { ForwardAdminStepDto } from './dto/forward-admin-step.dto';
import { ListWorkflowsDto } from './dto/list-workflows.dto';
import {
  WorkflowResponseDto,
  PaginatedWorkflowsDto,
  TimelineEventResponseDto,
  AdminCycleResponseDto,
} from './dto/workflow-response.dto';

import { OrgMember, SuperAdminOnly, JwtPayloadParam, JwtPayload, PermissionsGuard, RequirePermission } from '@sgd/common';

/**
 * IMPORTANTE — Orden de rutas:
 * Las rutas con path literal (/my-tasks, /my-available) DEBEN registrarse
 * ANTES de las rutas con parámetros (/:id) para evitar conflictos de matching en NestJS.
 */
@ApiTags('Workflows')
@ApiBearerAuth('JWT')
@Controller('api/v1/workflows')
@UseGuards(PermissionsGuard)
export class WorkflowsController {
  constructor(
    private readonly workflowsService: WorkflowsService,
    private readonly approvalService: WorkflowApprovalService,
    private readonly adminCycleService: WorkflowAdminCycleService,
    private readonly idempotencyService: IdempotencyService,
  ) {}

  /**
   * Envuelve una operación con soporte de idempotencia basada en header.
   * Si el cliente envía el mismo Idempotency-Key dentro de las 24 h,
   * devuelve la respuesta cacheada sin re-ejecutar la operación.
   */
  private async withIdempotency<T>(
    key: string | undefined,
    userId: string,
    fn: () => Promise<T>,
  ): Promise<T> {
    if (key) {
      const cached = await this.idempotencyService.get<T>(key, userId);
      if (cached !== null) return cached;
    }
    const result = await fn();
    if (key) {
      await this.idempotencyService.set(key, userId, result);
    }
    return result;
  }

  // ── Rutas estáticas PRIMERO ───────────────────────────────────────────────────

  @Get('stats')
  @OrgMember()
  @RequirePermission('WORKFLOWS', 'READ')
  @ApiOperation({ summary: 'Estadísticas de workflows por organización' })
  getStats(@JwtPayloadParam() user: JwtPayload) {
    return this.workflowsService.getStats(user.companyId!, user.sub);
  }

  @Get('admin/storage-per-org')
  @SuperAdminOnly()
  @ApiOperation({ summary: 'Storage de adjuntos de workflows agrupado por organización — solo super admin' })
  getStoragePerOrg() {
    return this.workflowsService.getStoragePerOrg();
  }

  @Get('my-tasks')
  @OrgMember()
  @RequirePermission('WORKFLOWS', 'READ')
  @ApiOperation({ summary: 'Tareas pendientes del usuario autenticado (aprobador o paso admin)' })
  @ApiResponse({ status: 200, type: [WorkflowResponseDto] })
  getMyTasks(@JwtPayloadParam() user: JwtPayload): Promise<WorkflowResponseDto[]> {
    return this.workflowsService.getMyTasks(user);
  }

  @Get('my-available')
  @OrgMember()
  @RequirePermission('WORKFLOWS', 'READ')
  @ApiOperation({ summary: 'Workflows disponibles para el usuario como usuario final' })
  @ApiResponse({ status: 200, type: [WorkflowResponseDto] })
  getMyAvailable(@JwtPayloadParam() user: JwtPayload): Promise<WorkflowResponseDto[]> {
    return this.workflowsService.getMyAvailable(user);
  }

  @Post('notify-no-final-users')
  @OrgMember()
  @RequirePermission('WORKFLOWS', 'WRITE')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({ summary: 'Notifica a los administradores que una tipología no tiene usuarios finales elegibles' })
  @ApiBody({ type: NotifyNoFinalUsersDto })
  @ApiResponse({ status: 204 })
  @ApiResponse({ status: 400, description: 'Validation error — invalid DTO fields' })
  notifyNoFinalUsers(
    @Body() dto: NotifyNoFinalUsersDto,
    @JwtPayloadParam() user: JwtPayload,
  ): Promise<void> {
    return this.workflowsService.notifyNoFinalUsers(dto, user);
  }

  // ── CRUD general ──────────────────────────────────────────────────────────────

  @Post()
  @OrgMember()
  @RequirePermission('WORKFLOWS', 'WRITE')
  @ApiOperation({ summary: 'Crear un nuevo workflow en estado DRAFT' })
  @ApiBody({ type: CreateWorkflowDto })
  @ApiResponse({ status: 201, type: WorkflowResponseDto })
  @ApiResponse({ status: 400, description: 'Validation error — invalid DTO fields' })
  @ApiResponse({ status: 409, description: 'Tipología no encontrada o sin usuarios finales configurados' })
  create(
    @Body() dto: CreateWorkflowDto,
    @JwtPayloadParam() user: JwtPayload,
  ): Promise<WorkflowResponseDto> {
    return this.workflowsService.create(dto, user);
  }

  @Get()
  @OrgMember()
  @RequirePermission('WORKFLOWS', 'MANAGE')
  @ApiOperation({ summary: 'Listar todos los workflows de la organización (requiere WORKFLOWS:MANAGE)' })
  @ApiResponse({ status: 200, type: PaginatedWorkflowsDto })
  findAll(
    @Query() dto: ListWorkflowsDto,
    @JwtPayloadParam() user: JwtPayload,
  ): Promise<PaginatedWorkflowsDto> {
    return this.workflowsService.findAll(dto, user);
  }

  @Get(':id')
  @OrgMember()
  @RequirePermission('WORKFLOWS', 'READ')
  @ApiOperation({ summary: 'Detalle de un workflow' })
  @ApiParam({ name: 'id', format: 'uuid' })
  @ApiResponse({ status: 200, type: WorkflowResponseDto })
  findOne(
    @Param('id', ParseUUIDPipe) id: string,
    @JwtPayloadParam() user: JwtPayload,
  ): Promise<WorkflowResponseDto> {
    return this.workflowsService.findOne(id, user);
  }

  @Patch(':id')
  @OrgMember()
  @RequirePermission('WORKFLOWS', 'WRITE')
  @ApiOperation({ summary: 'Actualizar workflow (solo en estado DRAFT)' })
  @ApiParam({ name: 'id', format: 'uuid' })
  @ApiBody({ type: UpdateWorkflowDto })
  @ApiResponse({ status: 200, type: WorkflowResponseDto })
  @ApiResponse({ status: 400, description: 'Validation error — invalid DTO fields' })
  @ApiResponse({ status: 409, description: 'Workflow no está en estado DRAFT — no puede modificarse' })
  update(
    @Param('id', ParseUUIDPipe) id: string,
    @Body() dto: UpdateWorkflowDto,
    @JwtPayloadParam() user: JwtPayload,
  ): Promise<WorkflowResponseDto> {
    return this.workflowsService.update(id, dto, user);
  }

  @Delete(':id')
  @OrgMember()
  @RequirePermission('WORKFLOWS', 'DELETE')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({ summary: 'Eliminar workflow (soft delete, solo DRAFT o CANCELLED)' })
  @ApiParam({ name: 'id', format: 'uuid' })
  @ApiResponse({ status: 204 })
  remove(
    @Param('id', ParseUUIDPipe) id: string,
    @JwtPayloadParam() user: JwtPayload,
  ): Promise<void> {
    return this.workflowsService.remove(id, user);
  }

  // ── Ciclo de aprobación ───────────────────────────────────────────────────────

  @Post(':id/start-approval')
  @OrgMember()
  @RequirePermission('WORKFLOWS', 'WRITE')
  @ApiOperation({ summary: 'Iniciar ciclo de aprobación (creador → PENDING_APPROVAL)' })
  @ApiParam({ name: 'id', format: 'uuid' })
  @ApiHeader(IDEMPOTENCY_HEADER)
  @ApiResponse({ status: 200, type: WorkflowResponseDto })
  async startApproval(
    @Headers('Idempotency-Key') idempotencyKey: string | undefined,
    @Param('id', ParseUUIDPipe) id: string,
    @JwtPayloadParam() user: JwtPayload,
  ): Promise<WorkflowResponseDto> {
    return this.withIdempotency(idempotencyKey, user.sub!, async () => {
      await this.approvalService.startApproval(id, user.sub!);
      return this.workflowsService.findOne(id, user);
    });
  }

  @Post(':id/approve')
  @OrgMember()
  @RequirePermission('WORKFLOWS', 'APPROVE')
  @ApiOperation({ summary: 'Aprobar el paso actual (aprobador actual)' })
  @ApiParam({ name: 'id', format: 'uuid' })
  @ApiHeader(IDEMPOTENCY_HEADER)
  @ApiBody({ type: ApproveWorkflowDto })
  @ApiResponse({ status: 200, type: WorkflowResponseDto })
  @ApiResponse({ status: 400, description: 'Validation error — invalid DTO fields' })
  @ApiResponse({ status: 409, description: 'Workflow no está en estado PENDING_APPROVAL o el usuario no es el aprobador actual' })
  async approve(
    @Headers('Idempotency-Key') idempotencyKey: string | undefined,
    @Param('id', ParseUUIDPipe) id: string,
    @Body() dto: ApproveWorkflowDto,
    @JwtPayloadParam() user: JwtPayload,
  ): Promise<WorkflowResponseDto> {
    return this.withIdempotency(idempotencyKey, user.sub!, async () => {
      await this.approvalService.approve(id, user.sub!, dto);
      return this.workflowsService.findOne(id, user);
    });
  }

  @Post(':id/reject')
  @OrgMember()
  @RequirePermission('WORKFLOWS', 'APPROVE')
  @ApiOperation({ summary: 'Rechazar con observaciones obligatorias (aprobador actual)' })
  @ApiParam({ name: 'id', format: 'uuid' })
  @ApiHeader(IDEMPOTENCY_HEADER)
  @ApiBody({ type: RejectWorkflowDto })
  @ApiResponse({ status: 200, type: WorkflowResponseDto })
  @ApiResponse({ status: 400, description: 'Validation error — observaciones requeridas y faltantes' })
  @ApiResponse({ status: 409, description: 'Workflow no está en estado PENDING_APPROVAL o el usuario no es el aprobador actual' })
  async reject(
    @Headers('Idempotency-Key') idempotencyKey: string | undefined,
    @Param('id', ParseUUIDPipe) id: string,
    @Body() dto: RejectWorkflowDto,
    @JwtPayloadParam() user: JwtPayload,
  ): Promise<WorkflowResponseDto> {
    return this.withIdempotency(idempotencyKey, user.sub!, async () => {
      await this.approvalService.reject(id, user.sub!, dto);
      return this.workflowsService.findOne(id, user);
    });
  }

  // ── Ciclos administrativos ────────────────────────────────────────────────────

  @Post(':id/admin-cycles')
  @OrgMember()
  @RequirePermission('WORKFLOWS', 'APPROVE')
  @ApiOperation({ summary: 'Iniciar ciclo administrativo (usuario final)' })
  @ApiParam({ name: 'id', format: 'uuid' })
  @ApiHeader(IDEMPOTENCY_HEADER)
  @ApiBody({ type: CreateAdminCycleDto })
  @ApiResponse({ status: 201, type: AdminCycleResponseDto })
  @ApiResponse({ status: 400, description: 'Validation error — invalid DTO fields' })
  @ApiResponse({ status: 409, description: 'Workflow no está en estado APPROVED o el usuario no es un usuario final elegible' })
  @HttpCode(HttpStatus.CREATED)
  async createAdminCycle(
    @Headers('Idempotency-Key') idempotencyKey: string | undefined,
    @Param('id', ParseUUIDPipe) id: string,
    @Body() dto: CreateAdminCycleDto,
    @JwtPayloadParam() user: JwtPayload,
  ): Promise<AdminCycleResponseDto> {
    return this.withIdempotency(idempotencyKey, user.sub!, async () => {
      const cycle = await this.adminCycleService.createCycle(id, user.sub!, dto);
      return AdminCycleResponseDto.from(cycle);
    });
  }

  @Patch(':id/admin-cycles/:cycleId/steps/:stepId/complete')
  @OrgMember()
  @RequirePermission('WORKFLOWS', 'APPROVE')
  @ApiOperation({ summary: 'Completar paso administrativo (usuario admin asignado)' })
  @ApiParam({ name: 'id', format: 'uuid' })
  @ApiParam({ name: 'cycleId', format: 'uuid' })
  @ApiParam({ name: 'stepId', format: 'uuid' })
  @ApiHeader(IDEMPOTENCY_HEADER)
  @ApiBody({ type: CompleteAdminStepDto })
  @ApiResponse({ status: 200 })
  @ApiResponse({ status: 400, description: 'Validation error — invalid DTO fields' })
  @ApiResponse({ status: 409, description: 'Paso no está en estado pendiente o el usuario no es el admin asignado' })
  completeAdminStep(
    @Headers('Idempotency-Key') idempotencyKey: string | undefined,
    @Param('id', ParseUUIDPipe) id: string,
    @Param('cycleId', ParseUUIDPipe) cycleId: string,
    @Param('stepId', ParseUUIDPipe) stepId: string,
    @Body() dto: CompleteAdminStepDto,
    @JwtPayloadParam() user: JwtPayload,
  ) {
    return this.withIdempotency(idempotencyKey, user.sub!, () =>
      this.adminCycleService.completeStep(id, cycleId, stepId, user.sub!, dto),
    );
  }

  @Post(':id/admin-cycles/:cycleId/steps/:stepId/forward')
  @OrgMember()
  @RequirePermission('WORKFLOWS', 'APPROVE')
  @ApiOperation({ summary: 'Reenviar paso a revisor opcional (revisor obligatorio activo)' })
  @ApiParam({ name: 'id', format: 'uuid' })
  @ApiParam({ name: 'cycleId', format: 'uuid' })
  @ApiParam({ name: 'stepId', format: 'uuid' })
  @ApiHeader(IDEMPOTENCY_HEADER)
  @ApiBody({ type: ForwardAdminStepDto })
  @ApiResponse({ status: 201, description: 'Paso reenviado al revisor opcional' })
  @ApiResponse({ status: 400, description: 'Validation error — invalid DTO fields' })
  @HttpCode(HttpStatus.CREATED)
  forwardAdminStep(
    @Headers('Idempotency-Key') idempotencyKey: string | undefined,
    @Param('id', ParseUUIDPipe) id: string,
    @Param('cycleId', ParseUUIDPipe) cycleId: string,
    @Param('stepId', ParseUUIDPipe) stepId: string,
    @Body() dto: ForwardAdminStepDto,
    @JwtPayloadParam() user: JwtPayload,
  ) {
    return this.withIdempotency(idempotencyKey, user.sub!, () =>
      this.adminCycleService.forwardStep(id, cycleId, stepId, user.sub!, dto),
    );
  }

  @Post(':id/admin-cycles/:cycleId/finalize')
  @OrgMember()
  @RequirePermission('WORKFLOWS', 'APPROVE')
  @ApiOperation({ summary: 'Confirmar finalización del ciclo administrativo (usuario final iniciador)' })
  @ApiParam({ name: 'id', format: 'uuid' })
  @ApiParam({ name: 'cycleId', format: 'uuid' })
  @ApiResponse({ status: 200, type: AdminCycleResponseDto })
  async finalizeAdminCycle(
    @Param('id', ParseUUIDPipe) id: string,
    @Param('cycleId', ParseUUIDPipe) cycleId: string,
    @JwtPayloadParam() user: JwtPayload,
  ): Promise<AdminCycleResponseDto> {
    const cycle = await this.adminCycleService.finalizeCycle(id, cycleId, user.sub);
    return AdminCycleResponseDto.from(cycle);
  }

  // ── Omitir ciclo de revisión ──────────────────────────────────────────────────

  @Post(':id/skip-review-cycle')
  @OrgMember()
  @RequirePermission('WORKFLOWS', 'APPROVE')
  @ApiOperation({ summary: 'Omitir ciclo de revisión y pasar directamente a AVAILABLE (usuario final)' })
  @ApiParam({ name: 'id', format: 'uuid' })
  @ApiHeader(IDEMPOTENCY_HEADER)
  @ApiResponse({ status: 200, type: WorkflowResponseDto })
  async skipReviewCycle(
    @Headers('Idempotency-Key') idempotencyKey: string | undefined,
    @Param('id', ParseUUIDPipe) id: string,
    @JwtPayloadParam() user: JwtPayload,
  ): Promise<WorkflowResponseDto> {
    return this.withIdempotency(idempotencyKey, user.sub!, async () => {
      await this.adminCycleService.skipReviewCycle(id, user.sub!);
      return this.workflowsService.findOne(id, user);
    });
  }

  // ── Cierre ────────────────────────────────────────────────────────────────────

  @Post(':id/close')
  @OrgMember()
  @RequirePermission('WORKFLOWS', 'APPROVE')
  @ApiOperation({ summary: 'Cerrar definitivamente el workflow (usuario final)' })
  @ApiParam({ name: 'id', format: 'uuid' })
  @ApiHeader(IDEMPOTENCY_HEADER)
  @ApiBody({ type: CloseWorkflowDto })
  @ApiResponse({ status: 200, type: WorkflowResponseDto })
  @ApiResponse({ status: 400, description: 'Validation error — invalid DTO fields' })
  @ApiResponse({ status: 409, description: 'Workflow no puede cerrarse en su estado actual' })
  async close(
    @Headers('Idempotency-Key') idempotencyKey: string | undefined,
    @Param('id', ParseUUIDPipe) id: string,
    @Body() dto: CloseWorkflowDto,
    @JwtPayloadParam() user: JwtPayload,
  ): Promise<WorkflowResponseDto> {
    return this.withIdempotency(idempotencyKey, user.sub!, async () => {
      await this.adminCycleService.closeWorkflow(id, user.sub!, dto);
      return this.workflowsService.findOne(id, user);
    });
  }

  // ── Trazabilidad ──────────────────────────────────────────────────────────────

  @Get(':id/timeline')
  @OrgMember()
  @RequirePermission('WORKFLOWS', 'READ')
  @ApiOperation({ summary: 'Línea de tiempo completa del workflow' })
  @ApiParam({ name: 'id', format: 'uuid' })
  @ApiResponse({ status: 200, type: [TimelineEventResponseDto] })
  getTimeline(
    @Param('id', ParseUUIDPipe) id: string,
    @JwtPayloadParam() user: JwtPayload,
  ): Promise<TimelineEventResponseDto[]> {
    return this.workflowsService.getTimeline(id, user);
  }
}
