apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: gestor-documental
  labels:
    app: auth-service
    project: sgd
data:
  NODE_ENV: "development"
  PORT: "3000"

  # Base de datos PostgreSQL
  DB_HOST: "postgresql.sgd-infra.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "auth_db"

  # Redis
  REDIS_HOST: "redis-master.sgd-infra.svc.cluster.local"
  REDIS_PORT: "6379"

  # JWT
  JWT_EXPIRATION: "3600s"
  JWT_REFRESH_EXPIRATION: "12h"

  # Internal URL of user-service within the cluster
  USER_SERVICE_URL: "http://user-service.gestor-documental.svc.cluster.local"

  # Health
  HEALTH_PATH: "/health"
