apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service
  namespace: gestor-documental
  labels:
    app: document-service
    project: sgd
    version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-service
  template:
    metadata:
      labels:
        app: document-service
        project: sgd
        version: "1.0.0"
    spec:
      containers:
        - name: document-service
          image: document-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - configMapRef:
                name: document-service-config
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: document-service-secret
                  key: MONGODB_USERNAME
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: document-service-secret
                  key: MONGODB_PASSWORD
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: document-service-secret
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: document-service-secret
                  key: MINIO_SECRET_KEY
          startupProbe:
            httpGet:
              path: /health/startup
              port: 3000
            failureThreshold: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: 3000
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3000
            initialDelaySeconds: 0
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
      restartPolicy: Always
