apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-service-config
  namespace: gestor-documental
  labels:
    app: audit-service
    project: sgd
data:
  NODE_ENV: "development"
  PORT: "3000"

  # Elasticsearch
  # elastic/elasticsearch chart crea el Service como "elasticsearch-master"
  ELASTICSEARCH_NODE: "http://elasticsearch-master.sgd-infra.svc.cluster.local:9200"
  ELASTICSEARCH_INDEX: "sgd-audit-logs"

  # Kafka
  KAFKA_BROKERS: "kafka.sgd-infra.svc.cluster.local:9092"
  KAFKA_GROUP_ID: "audit-service-group"
  KAFKA_CLIENT_ID: "audit-service"

  HEALTH_PATH: "/health"
