apiVersion: v1
kind: Secret
metadata:
  name: audit-service-secret
  namespace: gestor-documental
  labels:
    app: audit-service
    project: sgd
type: Opaque
stringData:
  ELASTICSEARCH_USERNAME: "elastic"
  ELASTICSEARCH_PASSWORD: "elastic_local"
